//===============================================
#ifndef _GInclude_
#define _GInclude_
//===============================================
typedef unsigned char uchar;
//===============================================
// system
#include <arpa/inet.h>
#include <cstdarg>
#include <cstring>
#include <dirent.h>
#include <fstream>
#include <iostream>
#include <map>
#include <memory>
#include <netdb.h>
#include <netinet/in.h>
#include <pthread.h>
#include <queue>
#include <vector>
#include <stack>
#include <cmath>
#include <signal.h>
#include <sstream>
#include <stdexcept>
#include <strings.h>
#include <time.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
// libxml2
#include <libxml/tree.h>
#include <libxml/xpath.h>
// mysql
#include <cppconn/driver.h>
#include <cppconn/exception.h>
#include <cppconn/resultset.h>
#include <cppconn/statement.h>
// poco
#include <Poco/Net/AcceptCertificateHandler.h>
#include <Poco/Net/ConsoleCertificateHandler.h>
#include <Poco/Net/Context.h>
#include <Poco/Net/DNS.h>
#include <Poco/Net/HostEntry.h>
#include <Poco/Net/HTMLForm.h>
#include <Poco/Net/HTTPCredentials.h>
#include <Poco/Net/HTTPClientSession.h>
#include <Poco/Net/HTTPMessage.h>
#include <Poco/Net/HTTPRequest.h>
#include <Poco/Net/HTTPRequestHandler.h>
#include <Poco/Net/HTTPResponse.h>
#include <Poco/Net/HTTPServer.h>
#include <Poco/Net/HTTPServerRequest.h>
#include <Poco/Net/HTTPServerRequestImpl.h>
#include <Poco/Net/HTTPServerResponse.h>
#include <Poco/Net/ICMPClient.h>
#include <Poco/Net/IPAddress.h>
#include <Poco/Net/KeyConsoleHandler.h>
#include <Poco/Net/MailMessage.h>
#include <Poco/Net/MailRecipient.h>
#include <Poco/Net/SecureSMTPClientSession.h>
#include <Poco/Net/SecureStreamSocket.h>
#include <Poco/Net/SSLManager.h>
#include <Poco/Net/StringPartSource.h>
#include <Poco/Net/TCPServer.h>
#include <Poco/Net/TCPServerConnection.h>
#include <Poco/Net/TCPServerConnectionFactory.h>
#include <Poco/Net/SecureServerSocket.h>
#include <Poco/Net/ServerSocket.h>
#include <Poco/Net/SocketReactor.h>
#include <Poco/Net/SocketAcceptor.h>
#include <Poco/Net/SocketNotification.h>
#include <Poco/Net/StreamSocket.h>
#include <Poco/Net/SocketStream.h>
#include <Poco/Net/X509Certificate.h>
//
#include <Poco/Util/Application.h>
#include <Poco/Util/ServerApplication.h>
//
#include <Poco/DateTimeFormat.h>
#include <Poco/DateTimeFormatter.h>
#include "Poco/Delegate.h"
#include <Poco/Exception.h>
#include <Poco/FIFOBuffer.h>
#include <Poco/Logger.h>
#include <Poco/NamedEvent.h>
#include <Poco/NObserver.h>
#include <Poco/NullStream.h>
#include <Poco/Path.h>
#include <Poco/Process.h>
#include <Poco/SharedPtr.h>
#include <Poco/StreamCopier.h>
#include <Poco/Timestamp.h>
#include <Poco/Thread.h>
#include <Poco/URI.h>
// curl
#include <curl/curl.h>
// base64
#include <base64.h>
// md5
#include <md5.h>
// openssl
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
// json-c
#include <json-c/json.h>
// includes
#include "GString.h"
//===============================================
#endif
//===============================================
