ui->treeMap->setColumnCount(2);
ui->treeMap->addHeader();
ui->treeMap->setData(0, "aH");
ui->treeMap->setData(1, "bH");
ui->treeMap->addRoot();
ui->treeMap->setData(0, "a1");
ui->treeMap->setData(1, "b1");
ui->treeMap->addChild();
ui->treeMap->setData(0, "a11");
ui->treeMap->setData(1, "b11");
ui->treeMap->initRoot();
ui->treeMap->addChild();
ui->treeMap->setData(0, "a12");
ui->treeMap->setData(1, "b12");
ui->treeMap->addChild();
ui->treeMap->setData(0, "a13");
ui->treeMap->setData(1, "b13");
ui->treeMap->addRoot();
ui->treeMap->setData(0, "a2");
ui->treeMap->setData(1, "b2");
ui->treeMap->addChild();
ui->treeMap->setData(0, "a21");
ui->treeMap->setData(1, "b21");
ui->treeMap->addChild();
ui->treeMap->setData(0, "a22");
ui->treeMap->setData(1, "b22");
