# ouvrir la liste des sources
sudo nano /etc/apt/sources.list

# commenter les lignes posant probleme
deb http://ports.ubuntu.com/ubuntu-ports/ jammy main restricted # auto generated by ubuntu-release-upgrader
deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main restricted # auto generated by ubuntu-release-upgrader
deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main restricted # auto generated by ubuntu-release-upgrader
